@startuml
class Notification {
    + Id : int <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Message : string <<get>> <<set>>
    + Status : string <<get>> <<set>>
    + ResponsibleUserOrGroup : string <<get>> <<set>>
}
Notification --> "CreatedAt" DateTime
@enduml
